//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class filmy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public filmy()
        {
            this.oceny = new HashSet<oceny>();
        }
    
        public int id { get; set; }
        public string nazwa { get; set; }
        public string opis { get; set; }
        public Nullable<short> rok_premiery { get; set; }
        public Nullable<int> budzet { get; set; }
        public int id_gatunek { get; set; }
        public int id_rezyser { get; set; }
    
        public virtual gatunki gatunki { get; set; }
        public virtual rezyserowie rezyserowie { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<oceny> oceny { get; set; }
    }
}
