//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MovieDBEntities : DbContext
    {
        public MovieDBEntities()
            : base("name=MovieDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<filmy> filmy { get; set; }
        public virtual DbSet<gatunki> gatunki { get; set; }
        public virtual DbSet<oceny> oceny { get; set; }
        public virtual DbSet<rezyserowie> rezyserowie { get; set; }
        public virtual DbSet<uzytkownicy> uzytkownicy { get; set; }
    }
}
