//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class oceny
    {
        public int id { get; set; }
        public int id_film { get; set; }
        public int id_uzytkownik { get; set; }
        public short ocena { get; set; }
        public string opis { get; set; }
    
        public virtual filmy filmy { get; set; }
        public virtual uzytkownicy uzytkownicy { get; set; }
    }
}
