//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class rezyserowie
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public rezyserowie()
        {
            this.filmy = new HashSet<filmy>();
        }
    
        public int id { get; set; }
        public string imie { get; set; }
        public string nazwisko { get; set; }
        public string kraj { get; set; }
        public Nullable<System.DateTime> data_urodzenia { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<filmy> filmy { get; set; }
    }
}
