//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class uzytkownicy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public uzytkownicy()
        {
            this.oceny = new HashSet<oceny>();
        }
    
        public int id { get; set; }
        public string nickname { get; set; }
        public string imie { get; set; }
        public string nazwisko { get; set; }
        public Nullable<int> ulubiony_gatunek { get; set; }
        public string password { get; set; }
    
        public virtual gatunki gatunki { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<oceny> oceny { get; set; }
    }
}
